# Numerical Computing with Python and Numpy

![](https://i.imgur.com/mg8O3kd.png)

This tutorial series is a beginner-friendly introduction to programming and data analysis using the Python programming language. These tutorials take a practical and coding-focused approach. The best way to learn the material is to execute the code and experiment with it yourself. 

## Working with numerical data

The "data" in *Data Analysis* typically refers to numerical data, e.g., stock prices, sales figures, sensor measurements, sports scores, database tables, etc. The [Numpy](https://numpy.org) library provides specialized data structures, functions, and other tools for numerical computing in Python. Let's work through an example to see why & how to use Numpy for working with numerical data.

> ##### Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in  millimeters) & average relative humidity (in percentage) as a linear equation. 
>
> `yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`


We're expressing the **yield of apples** as a weighted sum of the **temperature, rainfall, and humidity**. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might come up with reasonable values for the weights `w1`, `w2`, and `w3`. Here's an example set of values:

In [5]:
w1 , w2, w3 = 0.3, 0.2, 0.5

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record climate data for a region.

In [6]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [7]:
kanto_yield_apples = w1*kanto_temp + w2*kanto_rainfall + w3*kanto_humidity
kanto_yield_apples

56.8

In [8]:
print("The expected yield of apples in kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in kanto region is 56.8 tons per hectare.


**To make it slightly easier to perform the above computation for multiple regions, we can represent the climate data for each region as a vector, i.e., a list of numbers.**

In [9]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

The three numbers in each vector represent the temperature, rainfall, and humidity data, respectively. 

We can also represent the set of weights used in the formula as a vector.

In [10]:
weights = [w1, w2, w3]

**We can now write a function `crop_yield` to calcuate the yield of apples (or any other crop) given the climate data and the respective weights.**

In [11]:
def crop_yield(region, weights):
    result = 0
    for a, b in zip(region, weights):
        result += a * b
    return result

In [12]:
crop_yield(kanto, weights)

56.8

In [13]:
crop_yield(johto, weights)

76.9

In [14]:
crop_yield(hoenn, weights)

81.9

In [15]:
crop_yield(sinnoh, weights)

57.699999999999996

In [16]:
crop_yield(unova, weights)

74.9

## Going from Python lists to Numpy arrays


The calculation performed by the `crop_yield` (element-wise multiplication of two vectors and taking a sum of the results) is also called the *dot product*. Learn more about dot product here: https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length . 

The Numpy library provides a built-in function to compute the dot product of two vectors. However, we must first convert the lists into Numpy arrays.

Let's install the Numpy library using the `pip` package manager.

In [18]:
!pip install numpy --upgrade --quiet

In [20]:
import numpy as np

**We can now use the `np.array` function to create Numpy arrays.**

In [22]:
kanto = np.array([73, 67, 43])

In [23]:
kanto

array([73, 67, 43])

In [24]:
w1, w2, w3 = 0.3, 0.2, 0.5
weights = np.array([w1, w2, w3])

In [25]:
weights

array([0.3, 0.2, 0.5])

**Numpy arrays have the type `ndarray`.**

In [26]:
type(kanto)

numpy.ndarray

In [27]:
type(weights)

numpy.ndarray

**Just like lists, Numpy arrays support the indexing notation `[]`.**

In [28]:
weights

array([0.3, 0.2, 0.5])

In [29]:
weights[0]

0.3

In [30]:
kanto

array([73, 67, 43])

In [31]:
kanto[2]  # indexing start with zero.

43

In [32]:
len(kanto)

3

## Operating on Numpy arrays

**We can now compute the dot product of the two vectors using the `np.dot` function.**

In [34]:
# Dot Product Formula (x.y = x1*y1 +x2*y2 + x3*y3)
np.dot(kanto, weights)

56.8

**We can achieve the same result with low-level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the resulting numbers' sum.**

In [35]:
(kanto * weights).sum()

56.8

**The `*` operator performs an element-wise multiplication of two arrays if they have the same size. The `sum` method calculates the sum of numbers in an array.**

In [36]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [39]:
arr_3 = arr_1 * arr_2
arr_3

array([ 4, 10, 18])

In [40]:
arr_3.sum()

32

## Benefits of using Numpy arrays

Numpy arrays offer the following benefits over Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise, and intuitive mathematical expressions like `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yield`.

- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops that are interpreted at runtime

Here's a **comparison of dot products** performed using **Python loops vs. Numpy arrays** on two vectors with a million elements each.

In [41]:
# python lists
list_1 = list(range(1000000))
list_2 = list(range(1000000, 2000000))

np_array_1 = np.array(list_1)
np_array_2 = np.array(list_2)

In [42]:
%%time
result = 0
for x1, x2 in zip(list_1, list_2):
    result += x1*x2
result

CPU times: user 320 ms, sys: 248 µs, total: 320 ms
Wall time: 352 ms


833332333333500000

In [43]:
%%time
np.dot(np_array_1, np_array_2)

CPU times: user 3.12 ms, sys: 0 ns, total: 3.12 ms
Wall time: 1.88 ms


833332333333500000

As you can see, **using `np.dot` is 100 times faster than using a `for` loop.** 

This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.

## Multi-dimensional Numpy arrays 

We can now go one step further and represent the climate data for all the regions using a **single 2-dimensional Numpy array.**

In [46]:
climate_data = np.array([[73, 67, 43],
                       [91, 88, 64],
                       [87, 134, 58],
                       [102, 43, 37],
                       [69, 96, 70]])

In [47]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

If you've taken a linear algebra class in high school, you may recognize the above **2-d array as a matrix with five rows and three columns.** 

**Each row represents one region, and the columns represent temperature, rainfall, and humidity, respectively.**

Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">


In [49]:
climate_data.shape

(5, 3)

In [50]:
weights

array([0.3, 0.2, 0.5])

In [51]:
weights.shape

(3,)

In [59]:
arr_3D = np.array([
    [[11, 12, 13],
    [13, 14, 15]],
    [[15, 16, 17],
    [17, 18, 19.5]]
])

In [60]:
arr_3D.shape

(2, 2, 3)

**All the elements in a numpy array have the same data type.**

**You can check the data type of an array using the `.dtype` property.**

In [61]:
weights.dtype

dtype('float64')

In [62]:
climate_data.dtype

dtype('int64')

**If an array contains even a single floating point number, all the other elements are also converted to floats.**

In [63]:
arr_3D.dtype   # arr_3D has only one floating point element

dtype('float64')

We can now compute the predicted yields of apples in all the regions, using a single matrix multiplication between `climate_data` (a 5x3 matrix) and `weights` (a vector of length 3). Here's what it looks like visually:

<img src="https://i.imgur.com/LJ2WKSI.png" width="240">

**We can use the `np.matmul` function**

or 

**the `@` operator to perform matrix multiplication.**

In [64]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [65]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

## Working with CSV data files

Numpy also provides helper functions reading from & writing to files. **Let's download a file `climate.txt`, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:**


```
temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```

**This format of storing data is known as *comma-separated values* or CSV.** 

> **CSVs**: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)


**To read this file into a numpy array, we can use the `genfromtxt` function.**

In [4]:
!pip install numpy --upgrade --quiet

In [5]:
import numpy as np

In [6]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fda8e692250>)

In [8]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [9]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [10]:
climate_data.shape

(10000, 3)

We can now perform a **matrix multiplication using the `@` operator** to predict the yield of apples for the entire dataset using a given set of weights.

In [12]:
weights = np.array([0.3, 0.2, 0.5])

In [13]:
yields = climate_data @ weights

In [14]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [15]:
yields.shape

(10000,)

**Let's add the `yields` to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.**

In [17]:
fourth_column = yields.reshape(10000,1)

In [18]:
fourth_column

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [20]:
fourth_column.shape

(10000, 1)

In [26]:
climate_data.shape

(10000, 3)

In [28]:
climate_results = np.concatenate((climate_data, fourth_column), axis=1)

In [29]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [30]:
climate_results.shape

(10000, 4)

There are a couple of subtleties here:

* Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`. The `axis` argument specifies the dimension for concatenation.

*  The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function to change the shape of `yields` from `(10000,)` to `(10000,1)`.

Here's a visual explanation of `np.concatenate` along `axis=1` (can you guess what `axis=0` results in?):

<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

The best way to understand what a Numpy function does is to experiment with it and read the documentation to learn about its arguments & return values. Use the cells below to experiment with `np.concatenate` and `np.reshape`.

In [36]:
a = np.array([0, 1, 3, 5, 7, 9])

In [37]:
a

array([0, 1, 3, 5, 7, 9])

In [38]:
a.shape

(6,)

In [45]:
a_new = a.reshape(2, 3)

In [46]:
a_new

array([[0, 1, 3],
       [5, 7, 9]])

In [47]:
a_new.shape

(2, 3)

In [48]:
b = np.array([0, 2, 4, 6, 8, 10])

In [49]:
b

array([ 0,  2,  4,  6,  8, 10])

In [50]:
b_new = b.reshape(2, 3)

In [51]:
b_new

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [53]:
combined_arrays = np.concatenate((a_new, b_new), axis=1)

In [54]:
combined_arrays

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [55]:
combined_arrays.shape

(2, 6)

**Let's write the final results from our computation above back to a file using the `np.savetxt` function.**

In [56]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [58]:
climate_results.shape

(10000, 4)

In [59]:
np.savetxt('climate_results.txt',
          climate_results,
          fmt = '%.2f',
          delimiter = ',',
          header='temperature, rainfall, humidity, yield_apples',
          comments='')

In [62]:
np.genfromtxt('climate_results.txt', delimiter=',', skip_header=1)

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

The results are written back in the CSV format to the file `climate_results.txt`. 

```
temperature,rainfall,humidity,yeild_apples
25.00,76.00,99.00,72.20
39.00,65.00,70.00,59.70
59.00,45.00,77.00,65.20
84.00,63.00,38.00,56.80
...
```


Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

### Save and upload your notebook

Whether you're running this Jupyter notebook online or on your computer, it's essential to save your work from time to time. You can continue working on a saved notebook later or share it with friends and colleagues to let them execute your code. [Jovian](https://www.jovian.ai) offers an easy way of saving and sharing your Jupyter notebooks online.

In [63]:
!pip install jovian --upgrade --quiet

In [64]:
import jovian

In [65]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "usm811/07-python-numerical-computing-with-numpy" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/usm811/07-python-numerical-computing-with-numpy


'https://jovian.ai/usm811/07-python-numerical-computing-with-numpy'

## Arithmetic operations, broadcasting and comparison

Numpy arrays support arithmetic operators like `+`, `-`, `*`, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

In [72]:
arr_2 = np.array([
                  [1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 1, 2, 3]
                 ])

In [73]:
arr_3 = np.array([
                  [11, 12, 13, 14],
                  [15, 16, 17, 18],
                  [19, 11, 12, 13]
                ])

In [74]:
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [75]:
arr_2.shape

(3, 4)

In [76]:
# Adding a scalar to an array.
arr_2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [77]:
# Element wise subtraction
arr_3 - arr_2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [78]:
# Division by scalar
arr_2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [79]:
# Element wise multiplication
arr_2 * arr_3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [80]:
# Modulus with scalar (it find the remainder)
arr_2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

### Array Broadcasting

Numpy arrays also support *broadcasting*, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.

In [81]:
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 1, 2, 3]
])

In [82]:
arr2.shape

(3, 4)

In [83]:
arr4 = np.array([4, 5, 6, 7])

In [84]:
arr4.shape

(4,)

In [91]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [92]:
(arr2 + arr4).shape

(3, 4)

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated three times to match the shape `(3, 4)` of `arr2`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [93]:
arr5 = np.array([2, 4])

In [95]:
arr5.shape

(2,)

In [96]:
arr2.shape

(3, 4)

**These arrays can not add (broadcast) , as dimensions are not equal.**

In [97]:
# These arrays can not add , as dimensions are not equal.
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

### Array Comparison

Numpy arrays also support comparison operations like `==`, `!=`, `>` etc. The result is an array of booleans.

In [98]:
arr_1 = np.array([
    [1, 2, 3],
    [3, 4, 5]
])
arr_2 = np.array([
    [2, 2, 3],
    [1, 2, 5]
])

In [99]:
arr_1 == arr_2

array([[False,  True,  True],
       [False, False,  True]])

In [100]:
arr_1 != arr_2

array([[ True, False, False],
       [ True,  True, False]])

In [101]:
arr_1 >= arr_2

array([[False,  True,  True],
       [ True,  True,  True]])

In [102]:
arr_1 < arr_2

array([[ True, False, False],
       [False, False, False]])

**Array comparison is frequently used to count the number of equal elements in two arrays using the `sum` method.**

Remember that `True` evaluates to `1` and `False` evaluates to `0` when booleans are used in arithmetic operations.

In [103]:
(arr_1 == arr_2).sum()

3

## Array indexing and slicing

Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [108]:
arr_3 = np.array([
    [[11, 12, 13, 14],
    [13, 14, 15, 19]],
    
    [[15, 16, 17, 21],
     [63, 92, 36, 18]],
    
    
    [[98, 32, 81, 23],
     [17, 18, 19.5, 43]]
])

In [109]:
arr_3.shape

(3, 2, 4)

In [111]:
arr_3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [112]:
arr_3[1, 0]

array([15., 16., 17., 21.])

In [113]:
arr_3[1, 1]

array([63., 92., 36., 18.])

In [114]:
# single element
arr_3[1, 1, 2]

36.0

In [115]:
# sub-array using ranges
arr_3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [116]:
arr_3[1:, 0:1]   # last index in range is not included.

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [117]:
arr_3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [119]:
arr_3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [120]:
arr_3[1:, 1]

array([[63. , 92. , 36. , 18. ],
       [17. , 18. , 19.5, 43. ]])

In [121]:
arr_3[1:, 1, 3]

array([18., 43.])

In [122]:
arr_3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [123]:
arr_3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [124]:
arr_3[:2]

array([[[11., 12., 13., 14.],
        [13., 14., 15., 19.]],

       [[15., 16., 17., 21.],
        [63., 92., 36., 18.]]])

In [125]:
arr_3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [128]:
arr_3[2, 1, 3]

43.0

In [129]:
# indices more than dimension.
arr_3[2, 1, 2, 0]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

The notation and its results can seem confusing at first, so take your time to experiment and become comfortable with it. Use the cells below to try out some examples of array indexing and slicing, with different combinations of indices and ranges. Here are some more examples demonstrated visually:

<img src="https://scipy-lectures.org/_images/numpy_indexing.png" width="360">

In [130]:
a = np.array([
    [0, 1, 2, 3, 4, 5],
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55]
])

In [131]:
a[0, 3:5]

array([3, 4])

In [132]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [133]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [134]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## Other ways of creating Numpy arrays

Numpy also provides some handy functions to create arrays of desired shapes with fixed or random values. Check out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more.

In [135]:
# all zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [136]:
# all ones
np.ones((2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [137]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
# random vector
np.random.rand(5)

array([0.49969593, 0.0316416 , 0.0657004 , 0.97500094, 0.9247636 ])

In [140]:
np.random.rand(2, 3)

array([[0.12100043, 0.03696372, 0.69271776],
       [0.37106664, 0.49741105, 0.42951764]])

In [141]:
np.random.rand(3, 2, 4)

array([[[0.00706117, 0.35112054, 0.0224402 , 0.30071521],
        [0.21168046, 0.5833224 , 0.10252633, 0.85616276]],

       [[0.94466702, 0.33641308, 0.17761497, 0.75052335],
        [0.03038042, 0.36588861, 0.93321746, 0.84146679]],

       [[0.69001163, 0.71545647, 0.96219805, 0.3751375 ],
        [0.36095013, 0.86885977, 0.75487524, 0.08417333]]])

In [143]:
# fixed value
np.full([2, 3], 41)

array([[41, 41, 41],
       [41, 41, 41]])

In [144]:
# range with start, end and step.
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [151]:
# equally spaced numbers in a range

# starting value = 3
# ending value = 27
# total number of values = 9

np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])