# Assignment 2 - Numpy Array Operations

**NumPy is a Python library used for working with arrays.**

**It also has functions for working in domain of linear algebra, fourier transform, and matrices.**

**NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.**

**NumPy stands for Numerical Python.**

## Numpy Functions to deal with Mathematics:

List of function explained:
- function 01: `numpy.diag()`
- function 02: `numpy.transpose()`
- function 03: `ndarray.trace()`
- function 04: `numpy.linalg.matrix_rank()`
- function 05: `numpy.linalg.det()`
- `numpy.linalg.inv()` use to calculate the 'True Inverse' only of non-singular matrix arrays.
- `numpy.linalg.pinv()` use to calculate the 'Pseudo Inverse' of both singular and non-singular matrix arrays.
- `ndarray.flatten()` use to convert any multidimensional matrix array into single dimensional array.
- `numpy.linalg.eig()` use to find the eigenvalues.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "usm811/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/usm811/numpy-array-operations


'https://jovian.ai/usm811/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

# List of functions explained 
- function1 = numpy.diag()  # (change this)
- function2 = numpy.linalg.det()
- function3 = numpy.linalg.inv()
- function4 = numpy.linale.solve()
- function5 = numpy_array.flatten()

## Function 1 - numpy.diag()

This function is used to return:

- the array of main diagonal elements, if the n-D array is given in argument.
- the array of first diagonal elements, if rectangular array is given in argument.
- the value of optional argument k, decides that which array of diagonals will be returned.
- an n-D array, when 1-D array will pass as argument, with the elements of 1-D array as diagonal elements of n-D array.

**Example - 01:**

In [5]:
# Example 1 - working
mat_4 = np.arange(16).reshape(4,4)
mat_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
mat_4.shape

(4, 4)

In [7]:
np.diag(mat_4, k=0)

array([ 0,  5, 10, 15])

In [8]:
np.diag(mat_4, k=1)

array([ 1,  6, 11])

In [9]:
np.diag(mat_4, k=-2)

array([ 8, 13])

**Explanation of Example - 01:**

- `np.diag` function applied on 4-D array.
- It returned the array of main diagonal when k=0.
- It returned the 'first upper diagonal array' from the main diagonal when k=1.
- It returned the 'second lower diagonal array' from the main diagonal when k=-2.

**Example - 02:**

In [10]:
# Example 2 - working
arr_3 = np.array([2, 4, 6])
arr_3

array([2, 4, 6])

In [11]:
np.diag(arr_3)

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

**Explanation of Example - 02:**
- `np.diag` fuction applied on one dimensional array having 3 elements in it.
- It returned the 3-D array with the elements of the given 1-D array as diagonal elements and 'upper triangle' & 'lower triangle' of zeros.

**Example - 03:**

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
mat_3 = np.arange(9).reshape(3,3)
mat_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
mat_3.shape

(3, 3)

In [14]:
np.diag(mat_3, k=0)

array([0, 4, 8])

In [15]:
np.diag(mat_3, k=1)

array([1, 5])

In [16]:
np.diag(mat_3, k=2)

array([2])

In [17]:
np.diag(mat_3, k=3)   # return empty array.

array([], dtype=int64)

In [18]:
np.diag(mat_3, k=-1)

array([3, 7])

In [19]:
np.diag(mat_3, k=-3)   # return empty array.

array([], dtype=int64)

**Example - 04:**

In [20]:
# Example 4 - Limitations of getting Diagonal-Array when using rectangular array as input argument.
rectangle = np.arange(12).reshape(6,2)
rectangle

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
np.diag(rectangle)

array([0, 3])

In [22]:
np.diag(rectangle, k=1)

array([1])

In [23]:
np.diag(rectangle, k=2)   # returning empty array.

array([], dtype=int64)

In [24]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
np.diag(1)   # Breaking (When Argument is a number, not a list or numpy-array)

ValueError: Input must be 1- or 2-d.

In [26]:
np.diag('list argument')   # Breaking (When Argument is a list, not a numpy-array)

ValueError: Input must be 1- or 2-d.

In [27]:
np.diag()    # Breaking (When Argument is not passed)

TypeError: _diag_dispatcher() missing 1 required positional argument: 'v'

**Explanation of Example - 03 & 04:**
- `np.diag` function is applied on 3-D array with the values of k=0, 1, 2, 3, respectively.
- `np.diag` function is applied on rectangular array of dimension (6,2) with the values of k=0,1,2, respectively.
- `np.diag` function return **empty array** when we use the value k > n-1, for n-D array.
- `np.diag` function return **empty array** when we use the k < -(m-1) or k > n-1, for (m,n)-dimensional rectangular array.

- `np.diag` function breaks when no argument is passed, or the passed argument is not a list/numpy-array.

**Closing Comments:**
- `numpy.diag` function is used to extract the diagonal array from the n-D array.
- `numpy.diag` function is used to construct n-D diagonal array from 1-D array containing n-elements in it.
- We must need to pass the argument to the function in the form of list or numpy array.

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "usm811/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/usm811/numpy-array-operations


'https://jovian.ai/usm811/numpy-array-operations'

## Function 2 - numpy.linalg.det()

This function used to create an array with ones at and below the given diagonal and zeros elsewhere.

**Example - 01:**

In [30]:
# Example 1 - working
mat_3 = np.arange(9).reshape(3,3)
mat_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.linalg.det(mat_3)

0.0

**Explanation of Example-01:**
- A numpy array of equal dimension (equal number of rows and columns) is passed to the function to calculate it's determinant.

**Example - 02:**

In [32]:
# Example 2 - working
another_square_matrix = np.array([
    [-2, 4, 6, 8],
    [10, 12, 14, 16],
    [18, 20, -12, 24],
    [26, 28, 30, 32]
])

In [33]:
another_square_matrix

array([[ -2,   4,   6,   8],
       [ 10,  12,  14,  16],
       [ 18,  20, -12,  24],
       [ 26,  28,  30,  32]])

In [34]:
another_square_matrix.shape

(4, 4)

In [35]:
np.linalg.det(another_square_matrix)

-8704.000000000015

**Explanation of example - 02:**
- A random numpy array of equal dimension is passed to the function to calculate it's determinant.

**Example - 03:**

In [36]:
third_matrix_array = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
])
third_matrix_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [37]:
third_matrix_array.shape

(2, 3, 3)

In [38]:
np.linalg.det(third_matrix_array)

array([0., 0.])

In [39]:
# Example 3 - breaking (The passing argument should be equal dimensional array in last two dimensions.)
rectangular_array = np.array([[1, -2, 3], [4, -5, 6]])
rectangular_array

array([[ 1, -2,  3],
       [ 4, -5,  6]])

In [40]:
rectangular_array.shape

(2, 3)

In [41]:
np.linalg.det(rectangular_array)

LinAlgError: Last 2 dimensions of the array must be square

In [42]:
another_rectangular_array = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
another_rectangular_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
another_rectangular_array.shape

(3, 2)

In [44]:
np.linalg.det(another_rectangular_array)

LinAlgError: Last 2 dimensions of the array must be square

**Explanation of example - 03 (why it breaks and how to fix it)**
- When the equal dimensional array is not passed to the function, It raises the error.
- It can be fix by passing the equal dimensional array to the function.

**closing comments:**
- `numpy.linalg.det()` function is used to calculate the determinant of square matrices or equal dimensional array.
- I think that this function can also be work with some kind of **rectangular arrays**, because the error messages shows that **Last 2 dimensions of the array must be square**.
- But right now, I am not understanding about the other cases except square matrices/arrays.

In [ ]:
jovian.commit()

## Function 3 - numpy.linalg.inv()

This function is used to find the multiplicative inverse of the matrix array.

**Example - 01:**

In [45]:
# Example 1 - working
matrix_array_of_order_2 = np.array([[1, 2], [3, 4]])
matrix_array_of_order_2

array([[1, 2],
       [3, 4]])

In [46]:
np.linalg.det(matrix_array_of_order_2)

-2.0000000000000004

In [47]:
np.linalg.inv(matrix_array_of_order_2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Explanation of example - 01:**
- `numpy.linalg.inv()` function is used to compute the multiplicative inverse of a square matrix array of order 2.

In [48]:
# Example 2 - working
another_matrix_array = np.array([[[1., 2.], [3., 4.]], [[1, 3], [3, 5]]])
another_matrix_array

array([[[1., 2.],
        [3., 4.]],

       [[1., 3.],
        [3., 5.]]])

In [49]:
another_matrix_array.shape

(2, 2, 2)

In [50]:
np.linalg.inv(another_matrix_array)

array([[[-2.  ,  1.  ],
        [ 1.5 , -0.5 ]],

       [[-1.25,  0.75],
        [ 0.75, -0.25]]])

**Explanation of Example - 02:**
- `np.linalg.inv()` function is used to compute the multiplicative inverse of a 3-dimensional matrix array.

**Example - 03:**

In [51]:
# Example 3 - breaking (The determinant of the given matrix array is zero - Singular Matrix)
third_matrix_array = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
])
third_matrix_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [52]:
third_matrix_array.shape

(2, 3, 3)

In [53]:
np.linalg.det(third_matrix_array)

array([0., 0.])

In [54]:
np.linalg.inv(third_matrix_array)

LinAlgError: Singular matrix

**Explanation of Example - 03:**
- `np.linalg.inv()` can not use on a singular matrix array.
- To fix this issue, only possibility is that, apply the function on a non-singular matrix array.

**Closing Comments:**
- `numpy.linalg.inv()` function is used to find the multiplicative inverse of the non-singular matrix array.

In [ ]:
jovian.commit()

## Function 4 - numpy.linalg.solve()

- This function is used to solve the system of linear equations.
- This function calculates the exact 'x' of the matrix equation ax=b where a and b are given matrices.

**Example - 01:**

In [55]:
# Example 1 - working
a1 = np.arange(4).reshape(2,2)
a1

array([[0, 1],
       [2, 3]])

In [56]:
a1.shape

(2, 2)

In [57]:
b1 = np.arange(2)
b1

array([0, 1])

In [58]:
np.linalg.solve(a1,b1)

array([0.5, 0. ])

**Explanation of Example - 01:**
- `numpy.linalg.solve()` function is used to solve the system of two(02) linear equations with two(02) unknowns.

**Example - 02:**

In [59]:
# Example 2 - working
a2 = np.arange(8).reshape(2, 2, 2)
a2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
b2 = np.arange(2).reshape(1, 2)
b2

array([[0, 1]])

In [61]:
np.linalg.solve(a2, b2)

array([[ 0.5,  0. ],
       [ 2.5, -2. ]])

**Explanation of Example - 02:**
- `numpy.linalg.solve()` function is used to solve the system of three(03) linear equations with three(03) unknowns.

**Example - 03:**

In [62]:
# Example 3 - breaking (It breaks when the system of linear equations posses an inconsistent solution.)
a3 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a3.shape

(2, 3)

In [64]:
b3 = np.array([1, 2, 3]).reshape(1, 3)
b3

array([[1, 2, 3]])

In [65]:
b3.shape

(1, 3)

In [66]:
np.linalg.solve(a3, b3)

LinAlgError: Last 2 dimensions of the array must be square

**Explanation of Example - 03:**
- The function `numpy.linalg.solve()` raises the error when the number of equations are not equal to the number of unknowns.
- Such error can be avoid by using the consistent system of linear equations.

**Example - 04:**

In [67]:
# Example 4 - Breaking (In Ax=B, When the number of columns in matrix A is not equal to the number of columns in matrix B.)
a4 = np.arange(18).reshape(2, 3, 3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [68]:
a4.shape

(2, 3, 3)

In [69]:
b4 = np.arange(4).reshape(1, 4)
b4

array([[0, 1, 2, 3]])

In [70]:
b4.shape

(1, 4)

In [71]:
np.linalg.solve(a4, b4)

ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 4 is different from 3)

**Explanation of Example - 04:**
- We try to apply the system of linear equation with unequal last dimensions of matrix A and matrix B, in Ax=B.
- We can avoid such type of error by taking the last dimensions of matrix A and matrix B equal.

**Closing Comments:**
- `np.linalg.solve()` function is used to solve the system of linear equations.
- This function is successfully applied when the system of linear equation posses the consistent solution.
- This function is not useful in the case of inconsistent system of linear system.

In [ ]:
jovian.commit()

## Function 5 - .flatten()

This function is used to convert the multidimensional numpy array into single dimensional array for further calculations.

**Example - 01:**

In [72]:
# Example 1 - working
multidimensional_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
multidimensional_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
multidimensional_matrix.shape

(3, 3)

In [74]:
multidimensional_matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Explanation of Example - 01:**
- `numpy_array.flatten()` function applied to multidimensional array to convert it into one-dimensional array.

**Example - 02:**

In [75]:
# Example 2 - working
another_multidimensional_array = np.arange(16).reshape(2,4,2)
another_multidimensional_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [76]:
another_flatten_array = another_multidimensional_array.flatten()
another_flatten_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
another_flatten_array.shape

(16,)

**Explanation of Example - 02:**
- `numpy_array.flatten()` function applied to multidimensional array to convert it into one-dimensional array.

In [78]:
# Example 3 - breaking (The 'flatten()' function can be applied only on numpy arrays.)
random_list = [2, 3, 4]
random_list.flatten()

AttributeError: 'list' object has no attribute 'flatten'

In [79]:
empty_numpy_array = np.array([])
empty_numpy_array

array([], dtype=float64)

In [80]:
empty_numpy_array.flatten()

array([], dtype=float64)

**Explanation of Example - 03:**
- We applied `.flatten()` function to the list, but it raises error.
- `.flatten()` function can only be apply on the numpy arrays.

**Closing Comments:**
- `.flatten()' is simple function usually applied on the multidimensional numpy arrays to convert them into single dimensional array for further processing.

In [ ]:
jovian.commit()

## Conclusion

* In this notebook we have discussed some core functions related to the mathematical calculations specifically the calculations involves the matrices.
* Next, I have plan to explore the functions related to the statistical work.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/doc/stable/reference/
* https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8

In [81]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "usm811/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/usm811/numpy-array-operations


'https://jovian.ai/usm811/numpy-array-operations'